language: php
php:
  - 5.5
  - 5.6
  - hhvm
env:
  - DB_USERNAME="postgres" DB_PASSWORD=""
before-install:  
  - cp .env.travis .env
  - psql -c 'create database homestead;' -U postgres
  - psql -c 'create database homestead_test;' -U postgres
install: ./bin/setup.sh
cache:
  directories:
  - vendor
  - node_modules
  - resources/frontend/node_modules/
  - resources/frontend/bower_components/
