language: php

sudo: false

env:
  global:
    - DB_DATABASE=homestead_test
    - DB_USERNAME=postgres
    - DB_PASSWORD=
php:
  - 5.6
services:
  - postgresql
# try running against postgres 9.3
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'drop database if exists homestead_test;' -U postgres
  - psql -c 'create database homestead_test;' -U postgres
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry ./bin/setup.sh
  - php artisan migrate:status
  - yes | php artisan migrate
script: ./vendor/bin/phpunit
cache:
  directories:
    - $HOME/.composer/cache
    - vendor
    - node_modules
    - resources/frontend/node_modules/
    - resources/frontend/bower_components/
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9e9d9d82773d7d722a37
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
