language: php
php:
  - 5.5
  - 5.6
  - hhvm
services:
  - postgresql
# try running against postgres 9.3
addons:
  postgresql: "9.3"
env:
  - DB_USERNAME="postgres" DB_PASSWORD=""
before-install:  
  - cp .env.travis .env
  - psql -c 'drop database if exists homestead;' -U postgres
  - psql -c 'create database homestead;' -U postgres
  - psql -c 'GRANT ALL ON homestead TO postgres;' -U postgres
  - psql -c 'drop database if exists homestead_test;' -U postgres
  - psql -c 'create database homestead_test;' -U postgres
  - psql -c 'GRANT ALL ON homestead_test TO postgres;' -U postgres
install: 
  - php -i | grep postgre
  - php -m
  - cat .env
  - php artisan migrate:status
  - yes | php artisan migrate
  - ./bin/setup.sh
cache:
  directories:
    - vendor
    - node_modules
    - resources/frontend/node_modules/
    - resources/frontend/bower_components/
